site_name: WS Podcasts
site_author: Marcin Salski
site_description: >-
  Portfolio of my creative projects

repo_name: MarcinSalski/ws_portfolio
repo_url: https://github.com/MarcinSalski/ws_portfolio

theme:
  name: material
  palette:
    scheme: default 
    primary: rgb(244,6 67, 54)

nav:
- Welcome: index.md
- Book library:
  - "Brave New World Revisited by Aldous Huxley": BraveNewWorldRevisited/index.md
  - "The Road by Cormac McCarthy": TheRoad/index.md
- Episode library: OtherPodcasts/index.md



  

