site_name: WS Podcasts
site_author: Marcin Salski
site_description: >
  Portfolio of my creative projects

repo_name: MarcinSalski/ws_portfolio
repo_url: https://github.com/MarcinSalski/ws_portfolio

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - content.code.copy

# Podłączenie własnych stylów z kolorami RGB
extra_css: 
  - stylesheets/extra.css

nav:
  - Welcome: index.md
  - Books: Books/index.md
  - Episode library: Podcasts/index.md
