site_name: WS Podcasts
site_author: Marcin Salski
site_description: >
  Portfolio of my creative projects

repo_name: MarcinSalski/ws_portfolio
repo_url: https://github.com/MarcinSalski/ws_portfolio

nav:
  - Podcast: podcast.md


theme:
  name: material
  custom_dir: overrides


markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - meta
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.include
  - pymdownx.snippets


extra:
  episodes: !include data/episodes.yml