site_name: WS Podcasts 1
site_author: Marcin Salski
site_description: >-
  Portfolio of my creative projects

repo_name: MarcinSalski/ws_portfolio
repo_url: https://github.com/MarcinSalski/ws_portfolio

theme:
  name: material
  palette:
    primary: rgb(255, 64, 120)
    accent: rgb(33, 150, 243)

nav:
- Welcome: index.md
- Book library:
  - "Brave New World Revisited by Aldous Huxley": BraveNewWorldRevisited/index.md
  - "The Road by Cormac McCarthy": TheRoad/index.md
- Episode library: OtherPodcasts/index.md



  

